---
  # Uninstall Helm
- name: helm - remove helm releases
  shell: 
    cmd: helm ls -a --all-namespaces | awk 'NR > 1 { print "-n "$2, $1}' | xargs -L1 helm delete

- name: helm - Uninstall Helm
  file:
    state: absent
    path: /usr/local/bin/helm