---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prerequisites
    - role: k3s/download

- hosts: master
  roles:
    - role: k3s/master
      become: true

- hosts: node
  roles:
    - role: k3s/node
      become: true

- hosts: master
  roles:
    - role: k3s/postinstall
      become: true
    - role: helm
      become: true
    - role: dashboard
      become: true
    - role: cert-manager
      become: true
    - role: minio
      become: true