---
# Uninstall k3s software

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/uninstall
  post_tasks:
    - name: Reboot and wait for node to come back up
      become: true
      reboot:
        reboot_timeout: 360