---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: "Download to first master: manifest for metallb-{{ metallb_type }}"
  ansible.builtin.get_url:
    url: "{{ metallb_repository_url }}/{{ metallb_version }}/config/manifests/metallb-{{ metallb_type }}.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/metallb-crds.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Set image versions in manifest for metallb-{{ metallb_type }}
  ansible.builtin.replace:
    path: "/var/lib/rancher/k3s/server/manifests/metallb-crds.yaml"
    regexp: "{{ item.change | ansible.builtin.regex_escape }}"
    replace: "{{ item.to }}"
  with_items:
    - change: "metallb/speaker:{{ metallb_controller_version }}"
      to: "metallb/speaker:{{ metallb_speaker_version }}"
  loop_control:
    label: "{{ item.change }} => {{ item.to }}"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
