---
- name: Uninstall - Uninstall Hashicorp Vault
  shell: 
    cmd: helm uninstall vault --namespace {{ vault_namespace }}

#- name: Remove persistent data
#  file:
#    state: absent
#    path: "{{ persistent_data_path.split(\":\") | first | string }}"
#  when: remove_persistent_data